import { StandardMerkleTree } from "@openzeppelin/merkle-tree";
import fs from "fs";

// (1) load tree generated by createTree.ts
const tree = StandardMerkleTree.load(
  JSON.parse(fs.readFileSync("tree.json", "utf-8"))
);

// (2) loop through hashes of the tree (defined in tree.json)
for (const [i, v] of tree.entries()) {
  if (v[0] === "0x0000000000000000000000000000000000000010") {
    // (3) once the leaf is found, create a proof for it
    // ie. take all sibling hashes until root is reached
    const proof = tree.getProof(i);
    console.log("Value:", v);
    console.log("Proof:", proof);
  }
}
